import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Bebas_Neue, Anton } from 'next/font/google';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const bebasNeue = Bebas_Neue({
  subsets: ['latin'],  // You can add other subsets like 'cyrillic' if needed
  weight: '400',  // Regular weight for Bebas Neue
  variable: '--font-bebas-neue',  // Create a custom CSS variable for Bebas Neue
});

const anton = Anton({
  subsets: ['latin'],
  weight: '400',  // Regular weight for Anton
  variable: '--font-anton',  // Create a custom CSS variable for Anton
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
